"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'INSECURE')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if os.environ.get('DEBUG') == '1' else False

ALLOWED_HOSTS: list[str] = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'recipes',
    'authors',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'base_templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', # noqa: E501
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', # noqa: E501
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', # noqa: E501
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', # noqa: E501
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'base_static',
]

STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MESSAGE_TAGS = {
    constants.DEBUG: 'message-debug',
    constants.ERROR: 'message-error',
    constants.INFO: 'message-info',
    constants.SUCCESS: 'message-success',
    constants.WARNING: 'message-warning',
}

# from django.templatetags.static import static
# from django.urls import reverse_lazy
# from django.utils.translation import gettext_lazy as _

# UNFOLD = {
#     "SITE_TITLE": "Recipes",
#     "SITE_HEADER": "Recipes",
#     "SITE_SUBHEADER": "Appears under SITE_HEADER",
#     "SITE_URL": "/",
#     # "SITE_ICON": lambda request: static("icon.svg"),  # both modes, optimise for 32px height
#     "SITE_ICON": {
#         "light": lambda request: static("icon-light.svg"),  # light mode
#         "dark": lambda request: static("icon-dark.svg"),  # dark mode
#     },
#     # "SITE_LOGO": lambda request: static("logo.svg"),  # both modes, optimise for 32px height
#     "SITE_LOGO": {
#         "light": lambda request: static("logo-light.svg"),  # light mode
#         "dark": lambda request: static("logo-dark.svg"),  # dark mode
#     },
#     "SITE_SYMBOL": "speed",  # symbol from icon set
#     "SITE_FAVICONS": [
#         {
#             "rel": "icon",
#             "sizes": "32x32",
#             "type": "image/svg+xml",
#             "href": lambda request: static("favicon.svg"),
#         },
#     ],
#     "SHOW_HISTORY": True, # show/hide "History" button, default: True
#     "SHOW_VIEW_ON_SITE": True, # show/hide "View on site" button, default: True
#     "SHOW_BACK_BUTTON": False, # show/hide "Back" button on changeform in header, default: False
#     "ENVIRONMENT": "sample_app.environment_callback", # environment name in header
#     "ENVIRONMENT_TITLE_PREFIX": "sample_app.environment_title_prefix_callback", # environment name prefix in title tag
#     "DASHBOARD_CALLBACK": "sample_app.dashboard_callback",

#     "BORDER_RADIUS": "6px",
#     "COLORS": {
#         "base": {
#             "50": "oklch(98.5% .002 247.839)",
#             "100": "oklch(96.7% .003 264.542)",
#             "200": "oklch(92.8% .006 264.531)",
#             "300": "oklch(87.2% .01 258.338)",
#             "400": "oklch(70.7% .022 261.325)",
#             "500": "oklch(55.1% .027 264.364)",
#             "600": "oklch(44.6% .03 256.802)",
#             "700": "oklch(37.3% .034 259.733)",
#             "800": "oklch(27.8% .033 256.848)",
#             "900": "oklch(21% .034 264.665)",
#             "950": "oklch(13% .028 261.692)",
#         },
#         "primary": {
#             "50": "oklch(97.7% .014 308.299)",
#             "100": "oklch(94.6% .033 307.174)",
#             "200": "oklch(90.2% .063 306.703)",
#             "300": "oklch(82.7% .119 306.383)",
#             "400": "oklch(71.4% .203 305.504)",
#             "500": "oklch(62.7% .265 303.9)",
#             "600": "oklch(55.8% .288 302.321)",
#             "700": "oklch(49.6% .265 301.924)",
#             "800": "oklch(43.8% .218 303.724)",
#             "900": "oklch(38.1% .176 304.987)",
#             "950": "oklch(29.1% .149 302.717)",
#         },
#         "font": {
#             "subtle-light": "var(--color-base-500)",  # text-base-500
#             "subtle-dark": "var(--color-base-400)",  # text-base-400
#             "default-light": "var(--color-base-600)",  # text-base-600
#             "default-dark": "var(--color-base-300)",  # text-base-300
#             "important-light": "var(--color-base-900)",  # text-base-900
#             "important-dark": "var(--color-base-100)",  # text-base-100
#         },
#     },
#     "SIDEBAR": {
#         "show_search": True,  # Search in applications and models names
#         "command_search": True,  # Replace the sidebar search with the command search
#         "show_all_applications": False,  # Dropdown with all applications and models
#         "navigation": [
#             {
#                 "title": _("Navigation"),
#                 "separator": True,  # Top border
#                 "collapsible": True,  # Collapsible group of links
#                 "items": [
#                     {
#                         "title": _("Dashboard"),
#                         "icon": "dashboard",  # Supported icon set: https://fonts.google.com/icons
#                         "link": reverse_lazy("admin:index"),
#                         "permission": lambda request: request.user.is_superuser,
#                     },
#                     {
#                         "title": _("Users"),
#                         "icon": "people",
#                         "link": reverse_lazy("admin:auth_user_changelist"),
#                     },
#                 ],
#             },
#         ],
#     },
# }